; Renesas RA4M1 µCNC PlatformIO build environments

[env:RA4-UNO-R4]
framework = arduino
platform = platformio/renesas-ra@1.9.0
platform_packages = platformio/framework-arduinorenesas-uno@1.6.0
board = uno_r4_minima
; board_build.mcu = r7fa4m1ab
board_build.f_cpu = 48000000L
build_flags = 
	-D MCU=MCU_RA4M1
	-D BOARD=BOARD_UNO_R4
	-D F_CPU=48000000UL
	-D NO_USB
; src_filter = +<../../../cnc.h>
lib_ignore = WiFiS3, USB
lib_deps = 
    ${env.lib_deps}
	https://github.com/Paciente8159/uCNC-tinyusb.git#master
extra_scripts = 
	pre:uCNC/src/hal/boards/ra4/ra4_prebuild.py
