###############
# Virtual MCU #
###############

[env:EMULATOR_WINDOWS]
platform = native
framework =
platform_packages = platformio/toolchain-gccmingw32
; build_src_filter = 
;   +<*>
;   +<../makefiles/virtual/>
;   -<src/tinyusb>
;   -<src/hal/mcus/avr>
;   -<../makefiles/virtual/clib>
debug_tool = native
build_type = debug
debug_build_flags = -Og -g3
debug_init_cmds =
  run
build_flags = ${env.build_flags} -std=gnu99 -Wall -fdata-sections -ffunction-sections -fno-exceptions -Wl,--gc-sections -D MCU=MCU_VIRTUAL_WIN -D BOARD=BOARD_CUSTOM -lws2_32 -g -O0
; -D WIN_COM_NAME=COM1 -D SOCKET_PORT=34000 -lws2_32
extra_scripts = uCNC/src/hal/mcus/virtual/win_compiler.py

[env:EMULATOR_LINUX]
platform = native
framework =
; platform_packages = platformio/linux_x86_64@^1.2.0
build_src_filter = 
  +<*>
  -<src/hal/mcus/avr>
  -<src/hal/mcus/esp32>
  -<src/hal/mcus/esp32c3>
  -<src/hal/mcus/esp32s3>
  -<src/hal/mcus/esp32common>
  -<src/hal/mcus/esp8266>
  -<src/hal/mcus/lpc176x>
  -<src/hal/mcus/rp2040>
  -<src/hal/mcus/rp2350>
  -<src/hal/mcus/stm32f0x>
  -<src/hal/mcus/stm32f1x>
  -<src/hal/mcus/stm32f4x>
  -<src/hal/mcus/stm32h7x>
;   +<../makefiles/virtual/>
;   -<src/tinyusb>
  ; -<src/hal/mcus/avr>
;   -<../makefiles/virtual/clib>
debug_tool = native
build_type = debug
debug_build_flags = -Og -g3
debug_init_cmds =
  run
build_flags = ${env.build_flags} -std=gnu99 -Wall -fdata-sections -ffunction-sections -fno-exceptions -Wl,--gc-sections -D MCU=MCU_VIRTUAL_LINUX -D BOARD=BOARD_CUSTOM -lm -g -O0
; -D WIN_COM_NAME=COM1 -D SOCKET_PORT=34000 -lws2_32
; extra_scripts = uCNC/src/hal/mcus/virtual/win_compiler.py
