#ifndef CNC_HAL_RESET_H
#define CNC_HAL_RESET_H
#ifdef __cplusplus
extern "C"
{
#endif

#undef USE_STATIC_IP
#undef ENABLE_STEPPERS_DISABLE_TIMEOUT
#undef ENABLE_SKEW_COMPENSATION
#undef SKEW_COMPENSATION_XY_ONLY
#undef ENABLE_LINACT_PLANNER
#undef ENABLE_LINACT_COLD_START
#undef ENABLE_BACKLASH_COMPENSATION
#undef ABC_INDEP_FEED_CALC
#undef ENABLE_S_CURVE_ACCELERATION
#undef BRESENHAM_16BIT
#undef ENABLE_BIT_DEBUG_EXTRA_CMD
#undef ENABLE_EXTRA_SETTINGS_CMDS
#undef RAM_ONLY_SETTINGS
#undef STATUS_AUTOMATIC_REPORT_INTERVAL
#undef ENABLE_G39_H_MAPPING
#undef ENABLE_CANNED_CYCLES
#undef ENABLE_RS274NGC_EXPRESSIONS
#undef ENABLE_COOLANT
#undef ENABLE_LASER_PPI
#undef ENABLE_PLASMA_THC
#undef TOOL1
#undef SPINDLE_PWM
#undef SPINDLE_PWM_DIR
#undef SPINDLE_PWM_COOLANT_FLOOD
#undef SPINDLE_PWM_COOLANT_MIST
#undef FORCE_SOFT_POLLING
#undef ENABLE_RT_LIMITS_CHECKING
#undef ENABLE_RT_PROBE_CHECKING
#undef DISABLE_ALL_CONTROLS
#undef ESTOP_PULLUP_ENABLE
#undef SAFETY_DOOR_PULLUP_ENABLE
#undef FHOLD_PULLUP_ENABLE
#undef CS_RES_PULLUP_ENABLE
#undef DISABLE_ALL_LIMITS
#undef LIMIT_X_PULLUP_ENABLE
#undef LIMIT_Y_PULLUP_ENABLE
#undef LIMIT_Z_PULLUP_ENABLE
#undef LIMIT_X2_PULLUP_ENABLE
#undef LIMIT_Y2_PULLUP_ENABLE
#undef LIMIT_Z2_PULLUP_ENABLE
#undef LIMIT_A_PULLUP_ENABLE
#undef LIMIT_B_PULLUP_ENABLE
#undef LIMIT_C_PULLUP_ENABLE
#undef DISABLE_PROBE
#undef PROBE_PULLUP_ENABLE
#undef DISABLE_HAL_CONFIG_PROTECTION
#undef ENABLE_MULTI_STEPPER_AXIS
#undef SOFT_SPI_ENABLED
#undef ENCODERS
#undef ENABLE_ENCODER_RPM
#undef ENABLE_MAIN_LOOP_MODULES
#undef ENABLE_IO_MODULES
#undef ENABLE_PARSER_MODULES
#undef ENABLE_MOTION_CONTROL_MODULES
#undef ENABLE_PLANNER_MODULES
#undef DISABLE_SETTINGS_MODULES
#undef ENABLE_ITP_FEED_TASK
#undef ENABLE_ATC_HOOKS
#undef ENABLE_RT_SYNC_MOTIONS
#undef EMULATE_GRBL_STARTUP
#undef ENABLE_LONG_HOMING_CYCLE

#ifdef __cplusplus
}
#endif
#endif
