#ifndef CNC_HAL_OVERRIDES_H
#define CNC_HAL_OVERRIDES_H
#ifdef __cplusplus
extern "C"
{
#endif
#ifdef ENABLE_COOLANT
#undef ENABLE_COOLANT
#endif
#ifdef ENABLE_WIFI
#undef ENABLE_WIFI
#endif
#ifdef ENABLE_BLUETOOTH
#undef ENABLE_BLUETOOTH
#endif
#ifdef ENABLE_SKEW_COMPENSATION
#undef ENABLE_SKEW_COMPENSATION
#endif
#ifdef SKEW_COMPENSATION_XY_ONLY
#undef SKEW_COMPENSATION_XY_ONLY
#endif
#ifdef ENABLE_LINACT_PLANNER
#undef ENABLE_LINACT_PLANNER
#endif
#ifdef ENABLE_LINACT_COLD_START
#undef ENABLE_LINACT_COLD_START
#endif
#ifdef ENABLE_BACKLASH_COMPENSATION
#undef ENABLE_BACKLASH_COMPENSATION
#endif
#ifdef ENABLE_S_CURVE_ACCELERATION
#undef ENABLE_S_CURVE_ACCELERATION
#endif
#ifdef BRESENHAM_16BIT
#undef BRESENHAM_16BIT
#endif
#ifdef ENABLE_EXTRA_SYSTEM_CMDS
#undef ENABLE_EXTRA_SYSTEM_CMDS
#endif
#ifdef RAM_ONLY_SETTINGS
#undef RAM_ONLY_SETTINGS
#endif
#ifdef STATUS_AUTOMATIC_REPORT_INTERVAL_ENABLE
#undef STATUS_AUTOMATIC_REPORT_INTERVAL_ENABLE
#endif
#ifdef DISABLE_ALL_CONTROLS
#undef DISABLE_ALL_CONTROLS
#endif
#ifdef ESTOP_PULLUP_ENABLE
#undef ESTOP_PULLUP_ENABLE
#endif
#define ESTOP_PULLUP_ENABLE
#ifdef SAFETY_DOOR_PULLUP_ENABLE
#undef SAFETY_DOOR_PULLUP_ENABLE
#endif
#define SAFETY_DOOR_PULLUP_ENABLE
#ifdef FHOLD_PULLUP_ENABLE
#undef FHOLD_PULLUP_ENABLE
#endif
#define FHOLD_PULLUP_ENABLE
#ifdef CS_RES_PULLUP_ENABLE
#undef CS_RES_PULLUP_ENABLE
#endif
#define CS_RES_PULLUP_ENABLE
#ifdef DISABLE_ALL_LIMITS
#undef DISABLE_ALL_LIMITS
#endif
#ifdef LIMIT_X_DISABLE
#undef LIMIT_X_DISABLE
#endif
#ifdef LIMIT_Y_DISABLE
#undef LIMIT_Y_DISABLE
#endif
#ifdef LIMIT_Z_DISABLE
#undef LIMIT_Z_DISABLE
#endif
#ifdef LIMIT_X2_DISABLE
#undef LIMIT_X2_DISABLE
#endif
#ifdef LIMIT_Y2_DISABLE
#undef LIMIT_Y2_DISABLE
#endif
#ifdef LIMIT_Z2_DISABLE
#undef LIMIT_Z2_DISABLE
#endif
#ifdef LIMIT_X_PULLUP_ENABLE
#undef LIMIT_X_PULLUP_ENABLE
#endif
#define LIMIT_X_PULLUP_ENABLE
#ifdef LIMIT_Y_PULLUP_ENABLE
#undef LIMIT_Y_PULLUP_ENABLE
#endif
#define LIMIT_Y_PULLUP_ENABLE
#ifdef LIMIT_Z_PULLUP_ENABLE
#undef LIMIT_Z_PULLUP_ENABLE
#endif
#define LIMIT_Z_PULLUP_ENABLE
#ifdef LIMIT_X2_PULLUP_ENABLE
#undef LIMIT_X2_PULLUP_ENABLE
#endif
#define LIMIT_X2_PULLUP_ENABLE
#ifdef LIMIT_Y2_PULLUP_ENABLE
#undef LIMIT_Y2_PULLUP_ENABLE
#endif
#define LIMIT_Y2_PULLUP_ENABLE
#ifdef LIMIT_Z2_PULLUP_ENABLE
#undef LIMIT_Z2_PULLUP_ENABLE
#endif
#define LIMIT_Z2_PULLUP_ENABLE
#ifdef DISABLE_PROBE
#undef DISABLE_PROBE
#endif
#ifdef PROBE_PULLUP_ENABLE
#undef PROBE_PULLUP_ENABLE
#endif
#ifdef ENABLE_DUAL_DRIVE_AXIS
#undef ENABLE_DUAL_DRIVE_AXIS
#endif
#ifdef DUAL_DRIVE0_AXIS
#undef DUAL_DRIVE0_AXIS
#endif
#ifdef DUAL_DRIVE0_STEPPER
#undef DUAL_DRIVE0_STEPPER
#endif
#ifdef DUAL_DRIVE0_ENABLE_SELFSQUARING
#undef DUAL_DRIVE0_ENABLE_SELFSQUARING
#endif
#ifdef DUAL_DRIVE1_AXIS
#undef DUAL_DRIVE1_AXIS
#endif
#ifdef DUAL_DRIVE1_STEPPER
#undef DUAL_DRIVE1_STEPPER
#endif
#ifdef DUAL_DRIVE1_ENABLE_SELFSQUARING
#undef DUAL_DRIVE1_ENABLE_SELFSQUARING
#endif
#ifdef TOOL1
#undef TOOL1
#endif
#define TOOL1 spindle_pwm
#ifdef SPINDLE_PWM
#undef SPINDLE_PWM
#endif
#define SPINDLE_PWM PWM0
#ifdef SPINDLE_PWM_DIR
#undef SPINDLE_PWM_DIR
#endif
#define SPINDLE_PWM_DIR DOUT0
#ifdef ENABLE_LASER_PPI
#undef ENABLE_LASER_PPI
#endif
#ifdef SOFT_SPI_CLK
#undef SOFT_SPI_CLK
#endif
#define SOFT_SPI_CLK DOUT30
#ifdef SOFT_SPI_SDO
#undef SOFT_SPI_SDO
#endif
#define SOFT_SPI_SDO DOUT29
#ifdef SOFT_SPI_SDI
#undef SOFT_SPI_SDI
#endif
#define SOFT_SPI_SDI DIN29
#ifdef STEPPER0_HAS_TMC
#undef STEPPER0_HAS_TMC
#endif
#ifdef STEPPER0_DRIVER_TYPE
#undef STEPPER0_DRIVER_TYPE
#endif
#define STEPPER0_DRIVER_TYPE 2208
#ifdef STEPPER0_TMC_INTERFACE
#undef STEPPER0_TMC_INTERFACE
#endif
#define STEPPER0_TMC_INTERFACE TMC_UART
#ifdef STEPPER0_UART_TX
#undef STEPPER0_UART_TX
#endif
#define STEPPER0_UART_TX DOUT20
#ifdef STEPPER0_UART_RX
#undef STEPPER0_UART_RX
#endif
#define STEPPER0_UART_RX DIN20
#ifdef STEPPER0_SPI_CS
#undef STEPPER0_SPI_CS
#endif
#define STEPPER0_SPI_CS DOUT20
#ifdef STEPPER0_CURRENT_MAX
#undef STEPPER0_CURRENT_MAX
#endif
#define STEPPER0_CURRENT_MAX 750
#ifdef STEPPER0_MICROSTEP
#undef STEPPER0_MICROSTEP
#endif
#define STEPPER0_MICROSTEP 16
#ifdef STEPPER0_RSENSE
#undef STEPPER0_RSENSE
#endif
#define STEPPER0_RSENSE null
#ifdef STEPPER0_HOLD_MULT
#undef STEPPER0_HOLD_MULT
#endif
#define STEPPER0_HOLD_MULT 0.7
#ifdef STEPPER0_STEALTHCHOP_THERSHOLD
#undef STEPPER0_STEALTHCHOP_THERSHOLD
#endif
#define STEPPER0_STEALTHCHOP_THERSHOLD 0
#ifdef STEPPER0_ENABLE_INTERPLATION
#undef STEPPER0_ENABLE_INTERPLATION
#endif
#ifdef STEPPER0_STALL_SENSITIVITY
#undef STEPPER0_STALL_SENSITIVITY
#endif
#define STEPPER0_STALL_SENSITIVITY 10
#ifdef STEPPER1_HAS_TMC
#undef STEPPER1_HAS_TMC
#endif
#ifdef STEPPER1_DRIVER_TYPE
#undef STEPPER1_DRIVER_TYPE
#endif
#define STEPPER1_DRIVER_TYPE 2208
#ifdef STEPPER1_TMC_INTERFACE
#undef STEPPER1_TMC_INTERFACE
#endif
#define STEPPER1_TMC_INTERFACE TMC_UART
#ifdef STEPPER1_UART_TX
#undef STEPPER1_UART_TX
#endif
#define STEPPER1_UART_TX DOUT21
#ifdef STEPPER1_UART_RX
#undef STEPPER1_UART_RX
#endif
#define STEPPER1_UART_RX DIN21
#ifdef STEPPER1_SPI_CS
#undef STEPPER1_SPI_CS
#endif
#define STEPPER1_SPI_CS DOUT21
#ifdef STEPPER1_CURRENT_MAX
#undef STEPPER1_CURRENT_MAX
#endif
#define STEPPER1_CURRENT_MAX 750
#ifdef STEPPER1_MICROSTEP
#undef STEPPER1_MICROSTEP
#endif
#define STEPPER1_MICROSTEP 16
#ifdef STEPPER1_RSENSE
#undef STEPPER1_RSENSE
#endif
#define STEPPER1_RSENSE null
#ifdef STEPPER1_HOLD_MULT
#undef STEPPER1_HOLD_MULT
#endif
#define STEPPER1_HOLD_MULT 0.7
#ifdef STEPPER1_STEALTHCHOP_THERSHOLD
#undef STEPPER1_STEALTHCHOP_THERSHOLD
#endif
#define STEPPER1_STEALTHCHOP_THERSHOLD 0
#ifdef STEPPER1_ENABLE_INTERPLATION
#undef STEPPER1_ENABLE_INTERPLATION
#endif
#ifdef STEPPER1_STALL_SENSITIVITY
#undef STEPPER1_STALL_SENSITIVITY
#endif
#define STEPPER1_STALL_SENSITIVITY 10
#ifdef STEPPER2_HAS_TMC
#undef STEPPER2_HAS_TMC
#endif
#ifdef STEPPER2_DRIVER_TYPE
#undef STEPPER2_DRIVER_TYPE
#endif
#define STEPPER2_DRIVER_TYPE 2208
#ifdef STEPPER2_TMC_INTERFACE
#undef STEPPER2_TMC_INTERFACE
#endif
#define STEPPER2_TMC_INTERFACE TMC_UART
#ifdef STEPPER2_UART_TX
#undef STEPPER2_UART_TX
#endif
#define STEPPER2_UART_TX DOUT22
#ifdef STEPPER2_UART_RX
#undef STEPPER2_UART_RX
#endif
#define STEPPER2_UART_RX DIN22
#ifdef STEPPER2_SPI_CS
#undef STEPPER2_SPI_CS
#endif
#define STEPPER2_SPI_CS DOUT22
#ifdef STEPPER2_CURRENT_MAX
#undef STEPPER2_CURRENT_MAX
#endif
#define STEPPER2_CURRENT_MAX 750
#ifdef STEPPER2_MICROSTEP
#undef STEPPER2_MICROSTEP
#endif
#define STEPPER2_MICROSTEP 16
#ifdef STEPPER2_RSENSE
#undef STEPPER2_RSENSE
#endif
#define STEPPER2_RSENSE null
#ifdef STEPPER2_HOLD_MULT
#undef STEPPER2_HOLD_MULT
#endif
#define STEPPER2_HOLD_MULT 0.7
#ifdef STEPPER2_STEALTHCHOP_THERSHOLD
#undef STEPPER2_STEALTHCHOP_THERSHOLD
#endif
#define STEPPER2_STEALTHCHOP_THERSHOLD 0
#ifdef STEPPER2_ENABLE_INTERPLATION
#undef STEPPER2_ENABLE_INTERPLATION
#endif
#ifdef STEPPER2_STALL_SENSITIVITY
#undef STEPPER2_STALL_SENSITIVITY
#endif
#define STEPPER2_STALL_SENSITIVITY 10
#ifdef STEPPER3_HAS_TMC
#undef STEPPER3_HAS_TMC
#endif
#ifdef STEPPER3_DRIVER_TYPE
#undef STEPPER3_DRIVER_TYPE
#endif
#define STEPPER3_DRIVER_TYPE 2208
#ifdef STEPPER3_TMC_INTERFACE
#undef STEPPER3_TMC_INTERFACE
#endif
#define STEPPER3_TMC_INTERFACE TMC_UART
#ifdef STEPPER3_UART_TX
#undef STEPPER3_UART_TX
#endif
#define STEPPER3_UART_TX DOUT23
#ifdef STEPPER3_UART_RX
#undef STEPPER3_UART_RX
#endif
#define STEPPER3_UART_RX DIN23
#ifdef STEPPER3_SPI_CS
#undef STEPPER3_SPI_CS
#endif
#define STEPPER3_SPI_CS DOUT23
#ifdef STEPPER3_CURRENT_MAX
#undef STEPPER3_CURRENT_MAX
#endif
#define STEPPER3_CURRENT_MAX 750
#ifdef STEPPER3_MICROSTEP
#undef STEPPER3_MICROSTEP
#endif
#define STEPPER3_MICROSTEP 16
#ifdef STEPPER3_RSENSE
#undef STEPPER3_RSENSE
#endif
#define STEPPER3_RSENSE null
#ifdef STEPPER3_HOLD_MULT
#undef STEPPER3_HOLD_MULT
#endif
#define STEPPER3_HOLD_MULT 0.7
#ifdef STEPPER3_STEALTHCHOP_THERSHOLD
#undef STEPPER3_STEALTHCHOP_THERSHOLD
#endif
#define STEPPER3_STEALTHCHOP_THERSHOLD 0
#ifdef STEPPER3_ENABLE_INTERPLATION
#undef STEPPER3_ENABLE_INTERPLATION
#endif
#ifdef STEPPER3_STALL_SENSITIVITY
#undef STEPPER3_STALL_SENSITIVITY
#endif
#define STEPPER3_STALL_SENSITIVITY 10
#ifdef STEPPER4_HAS_TMC
#undef STEPPER4_HAS_TMC
#endif
#ifdef STEPPER4_DRIVER_TYPE
#undef STEPPER4_DRIVER_TYPE
#endif
#define STEPPER4_DRIVER_TYPE 2208
#ifdef STEPPER4_TMC_INTERFACE
#undef STEPPER4_TMC_INTERFACE
#endif
#define STEPPER4_TMC_INTERFACE TMC_UART
#ifdef STEPPER4_UART_TX
#undef STEPPER4_UART_TX
#endif
#define STEPPER4_UART_TX DOUT24
#ifdef STEPPER4_UART_RX
#undef STEPPER4_UART_RX
#endif
#define STEPPER4_UART_RX DIN24
#ifdef STEPPER4_SPI_CS
#undef STEPPER4_SPI_CS
#endif
#define STEPPER4_SPI_CS DOUT24
#ifdef STEPPER4_CURRENT_MAX
#undef STEPPER4_CURRENT_MAX
#endif
#define STEPPER4_CURRENT_MAX 750
#ifdef STEPPER4_MICROSTEP
#undef STEPPER4_MICROSTEP
#endif
#define STEPPER4_MICROSTEP 16
#ifdef STEPPER4_RSENSE
#undef STEPPER4_RSENSE
#endif
#define STEPPER4_RSENSE null
#ifdef STEPPER4_HOLD_MULT
#undef STEPPER4_HOLD_MULT
#endif
#define STEPPER4_HOLD_MULT 0.7
#ifdef STEPPER4_STEALTHCHOP_THERSHOLD
#undef STEPPER4_STEALTHCHOP_THERSHOLD
#endif
#define STEPPER4_STEALTHCHOP_THERSHOLD 0
#ifdef STEPPER4_ENABLE_INTERPLATION
#undef STEPPER4_ENABLE_INTERPLATION
#endif
#ifdef STEPPER4_STALL_SENSITIVITY
#undef STEPPER4_STALL_SENSITIVITY
#endif
#define STEPPER4_STALL_SENSITIVITY 10
#ifdef STEPPER5_HAS_TMC
#undef STEPPER5_HAS_TMC
#endif
#ifdef STEPPER5_DRIVER_TYPE
#undef STEPPER5_DRIVER_TYPE
#endif
#define STEPPER5_DRIVER_TYPE 2208
#ifdef STEPPER5_TMC_INTERFACE
#undef STEPPER5_TMC_INTERFACE
#endif
#define STEPPER5_TMC_INTERFACE TMC_UART
#ifdef STEPPER5_UART_TX
#undef STEPPER5_UART_TX
#endif
#define STEPPER5_UART_TX DOUT25
#ifdef STEPPER5_UART_RX
#undef STEPPER5_UART_RX
#endif
#define STEPPER5_UART_RX DIN25
#ifdef STEPPER5_SPI_CS
#undef STEPPER5_SPI_CS
#endif
#define STEPPER5_SPI_CS DOUT25
#ifdef STEPPER5_CURRENT_MAX
#undef STEPPER5_CURRENT_MAX
#endif
#define STEPPER5_CURRENT_MAX 750
#ifdef STEPPER5_MICROSTEP
#undef STEPPER5_MICROSTEP
#endif
#define STEPPER5_MICROSTEP 16
#ifdef STEPPER5_RSENSE
#undef STEPPER5_RSENSE
#endif
#define STEPPER5_RSENSE null
#ifdef STEPPER5_HOLD_MULT
#undef STEPPER5_HOLD_MULT
#endif
#define STEPPER5_HOLD_MULT 0.7
#ifdef STEPPER5_STEALTHCHOP_THERSHOLD
#undef STEPPER5_STEALTHCHOP_THERSHOLD
#endif
#define STEPPER5_STEALTHCHOP_THERSHOLD 0
#ifdef STEPPER5_ENABLE_INTERPLATION
#undef STEPPER5_ENABLE_INTERPLATION
#endif
#ifdef STEPPER5_STALL_SENSITIVITY
#undef STEPPER5_STALL_SENSITIVITY
#endif
#define STEPPER5_STALL_SENSITIVITY 10
#ifdef STEPPER6_HAS_TMC
#undef STEPPER6_HAS_TMC
#endif
#ifdef STEPPER6_DRIVER_TYPE
#undef STEPPER6_DRIVER_TYPE
#endif
#define STEPPER6_DRIVER_TYPE 2208
#ifdef STEPPER6_TMC_INTERFACE
#undef STEPPER6_TMC_INTERFACE
#endif
#define STEPPER6_TMC_INTERFACE TMC_UART
#ifdef STEPPER6_UART_TX
#undef STEPPER6_UART_TX
#endif
#define STEPPER6_UART_TX DOUT26
#ifdef STEPPER6_UART_RX
#undef STEPPER6_UART_RX
#endif
#define STEPPER6_UART_RX DIN26
#ifdef STEPPER6_SPI_CS
#undef STEPPER6_SPI_CS
#endif
#define STEPPER6_SPI_CS DOUT26
#ifdef STEPPER6_CURRENT_MAX
#undef STEPPER6_CURRENT_MAX
#endif
#define STEPPER6_CURRENT_MAX 750
#ifdef STEPPER6_MICROSTEP
#undef STEPPER6_MICROSTEP
#endif
#define STEPPER6_MICROSTEP 16
#ifdef STEPPER6_RSENSE
#undef STEPPER6_RSENSE
#endif
#define STEPPER6_RSENSE null
#ifdef STEPPER6_HOLD_MULT
#undef STEPPER6_HOLD_MULT
#endif
#define STEPPER6_HOLD_MULT 0.7
#ifdef STEPPER6_STEALTHCHOP_THERSHOLD
#undef STEPPER6_STEALTHCHOP_THERSHOLD
#endif
#define STEPPER6_STEALTHCHOP_THERSHOLD 0
#ifdef STEPPER6_ENABLE_INTERPLATION
#undef STEPPER6_ENABLE_INTERPLATION
#endif
#ifdef STEPPER6_STALL_SENSITIVITY
#undef STEPPER6_STALL_SENSITIVITY
#endif
#define STEPPER6_STALL_SENSITIVITY 10
#ifdef STEPPER7_HAS_TMC
#undef STEPPER7_HAS_TMC
#endif
#ifdef STEPPER7_DRIVER_TYPE
#undef STEPPER7_DRIVER_TYPE
#endif
#define STEPPER7_DRIVER_TYPE 2208
#ifdef STEPPER7_TMC_INTERFACE
#undef STEPPER7_TMC_INTERFACE
#endif
#define STEPPER7_TMC_INTERFACE TMC_UART
#ifdef STEPPER7_UART_TX
#undef STEPPER7_UART_TX
#endif
#define STEPPER7_UART_TX DOUT27
#ifdef STEPPER7_UART_RX
#undef STEPPER7_UART_RX
#endif
#define STEPPER7_UART_RX DIN27
#ifdef STEPPER7_SPI_CS
#undef STEPPER7_SPI_CS
#endif
#define STEPPER7_SPI_CS DOUT27
#ifdef STEPPER7_CURRENT_MAX
#undef STEPPER7_CURRENT_MAX
#endif
#define STEPPER7_CURRENT_MAX 750
#ifdef STEPPER7_MICROSTEP
#undef STEPPER7_MICROSTEP
#endif
#define STEPPER7_MICROSTEP 16
#ifdef STEPPER7_RSENSE
#undef STEPPER7_RSENSE
#endif
#define STEPPER7_RSENSE null
#ifdef STEPPER7_HOLD_MULT
#undef STEPPER7_HOLD_MULT
#endif
#define STEPPER7_HOLD_MULT 0.7
#ifdef STEPPER7_STEALTHCHOP_THERSHOLD
#undef STEPPER7_STEALTHCHOP_THERSHOLD
#endif
#define STEPPER7_STEALTHCHOP_THERSHOLD 0
#ifdef STEPPER7_ENABLE_INTERPLATION
#undef STEPPER7_ENABLE_INTERPLATION
#endif
#ifdef STEPPER7_STALL_SENSITIVITY
#undef STEPPER7_STALL_SENSITIVITY
#endif
#define STEPPER7_STALL_SENSITIVITY 10
#ifdef ENABLE_MAIN_LOOP_MODULES
#undef ENABLE_MAIN_LOOP_MODULES
#endif
#define ENABLE_MAIN_LOOP_MODULES
#ifdef ENABLE_IO_MODULES
#undef ENABLE_IO_MODULES
#endif
#ifdef ENABLE_PARSER_MODULES
#undef ENABLE_PARSER_MODULES
#endif
#ifdef ENABLE_MOTION_CONTROL_MODULES
#undef ENABLE_MOTION_CONTROL_MODULES
#endif
#ifdef ENABLE_SETTINGS_MODULES
#undef ENABLE_SETTINGS_MODULES
#endif
#ifdef ENABLE_RT_SYNC_MOTIONS
#undef ENABLE_RT_SYNC_MOTIONS
#endif

#define LOAD_MODULES_OVERRIDE() ({LOAD_MODULE(graphic_lcd);})

#ifdef __cplusplus
}
#endif
#endif
