#ifndef CNC_HAL_RESET_H
#define CNC_HAL_RESET_H
#ifdef __cplusplus
extern "C"
{
#endif

#undef ENABLE_COOLANT
#undef ENABLE_SKEW_COMPENSATION
#undef SKEW_COMPENSATION_XY_ONLY
#undef ENABLE_LINACT_PLANNER
#undef ENABLE_LINACT_COLD_START
#undef ENABLE_BACKLASH_COMPENSATION
#undef S_CURVE_ACCELERATION_LEVEL
#undef BRESENHAM_16BIT
#undef ENABLE_PIN_DEBUG_EXTRA_CMD
#undef ENABLE_EXTRA_SETTINGS_CMDS
#undef RAM_ONLY_SETTINGS
#undef STATUS_AUTOMATIC_REPORT_INTERVAL_ENABLE
#undef ENABLE_G39_H_MAPPING
#undef ENABLE_CANNED_CYCLES
#undef ENABLE_RS274NGC_EXPRESSIONS
#undef FORCE_SOFT_POLLING
#undef DISABLE_ALL_CONTROLS
#undef ESTOP_PULLUP_ENABLE
#undef SAFETY_DOOR_PULLUP_ENABLE
#undef FHOLD_PULLUP_ENABLE
#undef CS_RES_PULLUP_ENABLE
#undef DISABLE_ALL_LIMITS
#undef LIMIT_X_DISABLE
#undef LIMIT_Y_DISABLE
#undef LIMIT_Z_DISABLE
#undef LIMIT_X2_DISABLE
#undef LIMIT_Y2_DISABLE
#undef LIMIT_Z2_DISABLE
#undef LIMIT_X_PULLUP_ENABLE
#undef LIMIT_Y_PULLUP_ENABLE
#undef LIMIT_Z_PULLUP_ENABLE
#undef LIMIT_X2_PULLUP_ENABLE
#undef LIMIT_Y2_PULLUP_ENABLE
#undef LIMIT_Z2_PULLUP_ENABLE
#undef ENABLE_RT_LIMITS_CHECKING
#undef DISABLE_ROTATIONAL_AXIS_LIMITS_AFTER_HOMING
#undef DISABLE_HAL_CONFIG_PROTECTION
#undef DISABLE_PROBE
#undef PROBE_PULLUP_ENABLE
#undef ENABLE_RT_PROBE_CHECKING
#undef ENABLE_MULTI_STEPPER_AXIS
#undef TOOL1
#undef SPINDLE_PWM
#undef SPINDLE_PWM_DIR
#undef ENABLE_LASER_PPI
#undef ENABLE_PLASMA_THC
#undef SOFT_SPI_ENABLED
#undef ENCODERS
#undef ENABLE_MAIN_LOOP_MODULES
#undef ENABLE_IO_MODULES
#undef ENABLE_PARSER_MODULES
#undef ENABLE_MOTION_CONTROL_MODULES
#undef ENABLE_RT_SYNC_MOTIONS
#undef ENABLE_ITP_FEED_TASK
#undef SD_CARD_INTERFACE
#undef SD_SPI_CS
#undef SD_CARD_DETECT_PIN
#undef FF_USE_LFN
#undef ENABLE_SETTINGS_ON_SD_SDCARD

#ifdef __cplusplus
}
#endif
#endif
