#ifndef ERROR_H
#define ERROR_H

#define OK 0

#define GCODE_BAD_NUMBER_FORMAT 1
#define GCODE_UNKNOWN_GCOMMAND 2
#define GCODE_UNSUPORTED_COMMAND 3
#define GCODE_MODAL_GROUP_VIOLATION 4
#define GCODE_INVALID_WORD 5
#define GCODE_WORD_REPEATED 6
#define GCODE_WORD_VALUE_ERROR 7
#define GCODE_NOCOMMAND_IN_LINE 8

#endif