name: PlatformIO CI Tests

on:
  push:

jobs:
  unit-tests:
    name: Linux Unit Tests
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v7

      - name: Cache pip
        uses: actions/cache@v5
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ hashFiles('**/requirements.txt') }}
          restore-keys: pip-${{ runner.os }}-

      - name: Cache PlatformIO
        uses: actions/cache@v5
        with:
          path: ~/.platformio
          key: pio-v2-${{ runner.os }}-${{ hashFiles('platformio.ini', 'uCNC/src/hal/boards/**/*.ini') }}

      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: "3.12"

      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install "platformio==6.1.18"

      - name: Run Linux unit tests
        run: pio test -e EMULATOR_LINUX_TEST

  build:
    name: Build & Test Firmware
    needs: unit-tests
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        boards:
          - LPC176X-RE-ARM
          - ESP8266-Wemos-D1-R2
          - AVR-UNO
          - ESP32-MKS-TINYBEE
          - STM32F0-Bluepill-F030C8
          - STM32F1-Bluepill-F103C8
          - AVR-RAMBO
          - RP2040-PICO-W
          - SAMD21-Wemos-M0
          - STM32F4-Blackpill-F401CC
          - STM32H7-Generic-STM32H750
          - AVR-MEGA2560-RAMPS-V1_4
          - RP2350-PICO2
          - ESP32-S3
          - ESP32-C3

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v7

      - name: Cache pip
        uses: actions/cache@v5
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ hashFiles('**/requirements.txt') }}
          restore-keys: pip-${{ runner.os }}-

      - name: Cache PlatformIO
        uses: actions/cache@v5
        with:
          path: ~/.platformio
          key: pio-v2-${{ runner.os }}-${{ hashFiles('platformio.ini', 'uCNC/src/hal/boards/**/*.ini') }}

      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: "3.12"

      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install "platformio==6.1.18"

      - name: Run PlatformIO Build
        run: pio run -e ${{ matrix.boards }}
